"""Add strategy_id to Bot model

Revision ID: 6ba607210060
Revises: 053f48dfbeb4
Create Date: 2025-06-19 21:13:44.723050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba607210060'
down_revision = '053f48dfbeb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
