"""Initial clean schema with unique constraints

Revision ID: ffd0cf4442ec
Revises: 
Create Date: 2025-06-26 15:36:40.297600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd0cf4442ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_name'], ['users.user_name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('bot_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bot_name'], ['bots.name'], ),
    sa.ForeignKeyConstraint(['user_name'], ['users.user_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('bots')
    op.drop_table('users')
    # ### end Alembic commands ###
